### ISSUE TITLE
Unable to open .ttp Files

### ISSUE THREAD

**Issue by chuckthegrunt** [Karlovsky120/7DaysProfileEditor#17]
I am unable to open .ttp files. It just throws a .net exception, I put that error message in the bug report.

4.6.2 Net Framework

[NET Exception.zip](https://github.com/Karlovsky120/7DaysProfileEditor/files/1150480/NET.Exception.zip)

**Comment by madmunki** [comment]
Can you upload the TTP file? It wasn't captured in the report.

Thanks!

**Comment by madmunki** [comment]
I found the issue, it will be fixed in 16.3.
