### ISSUE TITLE
Error when trying to start the program

### ISSUE THREAD

**Issue by A7IE** [Karlovsky120/7DaysProfileEditor#2]
https://i.gyazo.com/55d3a9b06b9f3c85d7fce47bd6bb6fbc.png

is there any way to fix this?

**Comment by Karlovsky120** [comment]
That is what I'd like to know, but I've been unable to find anyone who gets the error to help me. Are you the one I am looking for? I might be able to fix it if you give me some feedback.

**Comment by A7IE** [comment]
I'm willing to help

**Comment by Karlovsky120** [comment]
Could you send me a PM on 7DaysToDie forums?
Then we could find a way to chat and resolve it faster instead of ping-ponging here.

**Comment by Karlovsky120** [comment]
The program was compiled in VisualStudio 2013 with platform target set to AnyCPU. Changing this to 32-bit or 64-bit fixes the issue (in this case at least). Program will from now on be released for 32-bit platform, which should work on both 32bit and 64bit systems. Closing the issue.
