### ISSUE TITLE
Adware False Positive?

### ISSUE THREAD

**Issue by Gilthanaz** [Karlovsky120/7DaysProfileEditor#24]
Hi, 
I just downloaded the latest .exe and tried to run it, which causes windows (8.1) to block it and Avira Free Antivirus (Ver. 15.0.28.28 with signature file Ver. 8.14.19.146) to quarantine the 7DaysProfileEditor.exe and report it as 'Adware/Dotdo.yqnxe'. I'm pretty sure it's a false positive ;) But still, it might make some people jump... 
KR

**Comment by madmunki** [comment]
Odd, Ill contact them and figure out why. Thanks for the heads up.

**Comment by Guardian0982** [comment]
Norton didn't like it on my system either.  I'm using Windows 10.  I had to go back and undo the deletion and tell it to ignore it from future scans.
