### ISSUE TITLE
Stuck at Creating Player

### ISSUE THREAD

**Issue by ReigningRoyalty** [Karlovsky120/7DaysProfileEditor#26]
After using the program, I often get stuck at Creating Player after attempting to load the modified player into the world. Typically happens after stats/skills have been modded but not after inventory modifications.

**Comment by laughingsteam** [comment]
What version are you using? The latest? If you're using the Steam version, it'll most likely stay updated, so you'll be running 16.2, which this doesn't support fully. At least I haven't been able to get it to work

If you're seeing a Creating Player thing, is it a new profile or existing? With a modified profile, remember there are certain things you need first. For example, increasing Miner 69 to level 3 requires Mining Tools to be 80+ in level. There are dependencies I would check.

**Comment by ReigningRoyalty** [comment]
It's probably due to the fact I'm using the steam version ie 16.2
Thank you for the swift reply and take care
