### ISSUE TITLE
An item with the same key has already been added

### ISSUE THREAD

**Issue by GeneShogo** [Karlovsky120/7DaysProfileEditor#3]
Hey Karlovsky, when using the profile editor with Valmod Pack I get the below crash report when selecting the exe file for the game.

Time Stamp: 12/14/2016 6:50:37 PM
Message: An item with the same key has already been added.
Source: mscorlib
Inner Exception: 
Stack Trace:    at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at SevenDaysProfileEditor.Data.XmlData.GetSkills()
   at SevenDaysProfileEditor.Program.Initialize()
Target Site: Void ThrowArgumentException(System.ExceptionResource)

Here is the mod back im using and it is the only one I use. 
https://7daystodie.com/forums/showthread.php?31730-Valmod-Pack
Thanks in advance.

**Comment by Karlovsky120** [comment]
I'm sorry, I saw the message when I was at work and promptly forgot about it.

Off the top of my head, it seems there are two skills with the same name in the setup you are using.
Can you specify the exact version of the editor, the game and the mod you were using when the crash occurred? 

I'll see if I can reproduce the error and see what's going on.

**Comment by GeneShogo** [comment]
Np thank you for the response.

Game version: A15.1 (current Steam version)
Your editor: 1.15.0.1 (https://github.com/Karlovsky120/7DaysProfileEditor/tree/master/release/1.15.0.1/x64)
Current Valmod: A15 (https://github.com/7days2mod/Valmod-Overhaul/archive/master.zip)

Thanks in advance Karlovsky.

**Comment by Karlovsky120** [comment]
There is an error in progression.xml in valmod. It sets level requirement for unlocking "brickCNRFull" twice in Masonry skill.
Second time my program reads it, it gets confused.

I slapped him around a little bit and told him to get his act together.
It worked like a charm.
