### ISSUE TITLE
error opening application

### ISSUE THREAD

**Issue by thomasbonsirven** [Karlovsky120/7DaysProfileEditor#41]
hello,

impossible to open apps, on windows uodated.
[notopening.rpt.zip](https://github.com/Karlovsky120/7DaysProfileEditor/files/2757006/notopening.rpt.zip)
[notopening1.rpt.rpt.zip](https://github.com/Karlovsky120/7DaysProfileEditor/files/2757007/notopening1.rpt.rpt.zip)

please help me

**Comment by Karlovsky120** [comment]
Program only works on A16, and this is from A17.
I still have some work to do to support A17.

**Comment by thomasbonsirven** [comment]
Ok, i understand. Tell me if you need help/test/server ;)
Contact me in private message

Your project is important for me.
