### ISSUE TITLE
forged iron, steal , scrap iron, wood

### ISSUE THREAD

**Issue by OpaqueWindow** [Karlovsky120/7DaysProfileEditor#7]
these are some of the items that do not spawn

**Comment by Karlovsky120** [comment]
Sorry, I didn't get the notification about the issue.

I'm gonna need more data than that friend. Open the save that doesn't show the items and press help->send error report. That will create a *.7z file that you can upload somewhere and send me the link. I'll then be able to pinpoint the issue.

**Comment by OpaqueWindow** [comment]
my bad i found the issue i modified the value too far for the amount of
items allowed to carry of 1 item. would make it so they didn't spawn in.

**Comment by Karlovsky120** [comment]
Glad that's sorted out then. :)
