### ISSUE TITLE
Failed to Save

### ISSUE THREAD

**Issue by Anhnalex** [Karlovsky120/7DaysProfileEditor#8]
Please assist.
Thank you
![capture](https://cloud.githubusercontent.com/assets/27877599/25301054/2666288a-26e3-11e7-863f-f7745a2ba509.JPG)

**Comment by Karlovsky120** [comment]
I've fixed this two days ago (or so I believe). Is it still happening or did you use the older version?

**Comment by Anhnalex** [comment]
I downloaded the last version and it does not work.

**Comment by Karlovsky120** [comment]
Something went wrong when I was building the project and x86 builds must've failed without me noticing. I've re-uploaded everything, it should be fine now. Will close issue once confirmed.

**Comment by Anhnalex** [comment]
Thank you. It works now. I appreciate it.
