### ISSUE TITLE
Wants to load .exe

### ISSUE THREAD

**Issue by Seegras** [Karlovsky120/7DaysProfileEditor#9]
Upon starting it (in mono) wants to know the location of the file to open, and it insist the file be called 7DaysToDie.exe. 

I don't have that, because I'm on Linux in the first place. I just like to edit a *.ttp file. Compiling myself is of course also not really an option, as I have no visual studio (and no Makefile for compiling with mono is present).

So, how do I just edit a *.ttp file?

**Comment by Karlovsky120** [comment]
Hmmm, I never thought about linux. I needed to use some game files, and the easiest solution was to just ask the user for the exe and locate it that way.

Are there any other files in the root folder that are present on both Windows and Linux version?

As a quick fix, you can just create an empty file and call it "7DaysToDie.exe" and put it in the games root folder, the program only checks for the name anyway.
